import os
import uuid
from pathlib import Path

import pytest
from alembic import command
from alembic.config import Config
from sqlalchemy import create_engine, text
from sqlalchemy.exc import IntegrityError

pytestmark = pytest.mark.integration

TEST_DATABASE_URL = os.getenv("TEST_DATABASE_URL", "")
ALEMBIC_INI = Path(__file__).resolve().parents[2] / "alembic.ini"
TABLES = {"users", "sessions", "videos", "jobs", "job_results", "player_tracks"}


@pytest.fixture(scope="module")
def alembic_cfg() -> Config:
    if not TEST_DATABASE_URL:
        pytest.skip("TEST_DATABASE_URL not set")
    cfg = Config(str(ALEMBIC_INI))
    cfg.attributes["database_url"] = TEST_DATABASE_URL
    return cfg


@pytest.fixture(scope="module")
def engine(alembic_cfg):
    eng = create_engine(TEST_DATABASE_URL)
    command.downgrade(alembic_cfg, "base")
    command.upgrade(alembic_cfg, "head")
    yield eng
    eng.dispose()


@pytest.fixture
def conn(engine):
    # Every test runs in a transaction that is rolled back, so tests stay independent.
    with engine.connect() as connection:
        tx = connection.begin()
        yield connection
        tx.rollback()


def table_names(engine) -> set[str]:
    with engine.connect() as c:
        rows = c.execute(text("SELECT tablename FROM pg_tables WHERE schemaname = 'public'"))
        return {r[0] for r in rows} - {"alembic_version"}


def insert_user(conn, sub: str = "sub-1") -> uuid.UUID:
    return conn.execute(
        text("INSERT INTO users (provider, provider_sub) VALUES ('google', :s) RETURNING id"),
        {"s": sub},
    ).scalar_one()


def insert_video(conn, user_id: uuid.UUID) -> uuid.UUID:
    return conn.execute(
        text("INSERT INTO videos (user_id, source_type) VALUES (:u, 'upload') RETURNING id"),
        {"u": user_id},
    ).scalar_one()


def insert_job(conn, user_id: uuid.UUID, video_id: uuid.UUID, **cols) -> uuid.UUID:
    names = ["user_id", "video_id", *cols]
    params = {"user_id": user_id, "video_id": video_id, **cols}
    sql = (
        f"INSERT INTO jobs ({', '.join(names)}) "
        f"VALUES ({', '.join(':' + n for n in names)}) RETURNING id"
    )
    return conn.execute(text(sql), params).scalar_one()


def assert_rejected(conn, sql: str, params: dict, constraint: str) -> None:
    with pytest.raises(IntegrityError, match=constraint):
        with conn.begin_nested():
            conn.execute(text(sql), params)


def test_upgrade_downgrade_upgrade(alembic_cfg, engine):
    assert table_names(engine) == TABLES
    command.downgrade(alembic_cfg, "base")
    assert table_names(engine) == set()
    command.upgrade(alembic_cfg, "head")
    assert table_names(engine) == TABLES


def test_migrations_match_table_definitions(alembic_cfg, engine):
    # Raises AutogenerateDiffsDetected if db_tables.py and the revisions disagree.
    command.check(alembic_cfg)


def test_indexes_exist_and_claimable_is_partial(engine):
    with engine.connect() as c:
        defs = dict(
            c.execute(
                text(
                    "SELECT indexname, indexdef FROM pg_indexes "
                    "WHERE indexname IN ('ix_jobs_claimable', 'ix_jobs_user_created', "
                    "'ix_sessions_user')"
                )
            ).all()
        )
    assert set(defs) == {"ix_jobs_claimable", "ix_jobs_user_created", "ix_sessions_user"}
    assert "WHERE (status = ANY" in defs["ix_jobs_claimable"]
    assert "created_at DESC" in defs["ix_jobs_user_created"]


def test_job_defaults(conn):
    user_id = insert_user(conn)
    job_id = insert_job(conn, user_id, insert_video(conn, user_id))
    row = conn.execute(
        text("SELECT status, progress, attempts, max_attempts, config FROM jobs WHERE id = :j"),
        {"j": job_id},
    ).one()
    assert tuple(row) == ("queued", 0, 0, 3, {})


@pytest.mark.parametrize(
    ("cols", "constraint"),
    [
        ({"status": "done"}, "ck_jobs_status_valid"),
        ({"progress": 101}, "ck_jobs_progress_range"),
        ({"attempts": -1}, "ck_jobs_attempts_valid"),
        ({"status": "failed"}, "ck_jobs_failed_has_error"),
    ],
)
def test_job_check_constraints(conn, cols, constraint):
    user_id = insert_user(conn)
    video_id = insert_video(conn, user_id)
    names = ["user_id", "video_id", *cols]
    sql = f"INSERT INTO jobs ({', '.join(names)}) VALUES ({', '.join(':' + n for n in names)})"
    assert_rejected(conn, sql, {"user_id": user_id, "video_id": video_id, **cols}, constraint)


def test_failed_job_with_error_code_is_allowed(conn):
    user_id = insert_user(conn)
    insert_job(conn, user_id, insert_video(conn, user_id), status="failed", error_code="INTERNAL")


def test_video_source_rules(conn):
    user_id = insert_user(conn)
    assert_rejected(
        conn,
        "INSERT INTO videos (user_id, source_type) VALUES (:u, 'url')",
        {"u": user_id},
        "ck_videos_url_matches_source",
    )
    assert_rejected(
        conn,
        "INSERT INTO videos (user_id, source_type, source_url) VALUES (:u, 'upload', 'x')",
        {"u": user_id},
        "ck_videos_url_matches_source",
    )
    assert_rejected(
        conn,
        "INSERT INTO videos (user_id, source_type) VALUES (:u, 'ftp')",
        {"u": user_id},
        "ck_videos_source_type_valid",
    )


def test_unique_user_per_provider_sub(conn):
    insert_user(conn, "same")
    assert_rejected(
        conn,
        "INSERT INTO users (provider, provider_sub) VALUES ('google', 'same')",
        {},
        "uq_users_provider_provider_sub",
    )


def test_player_tracks_natural_key_and_team(conn):
    user_id = insert_user(conn)
    job_id = insert_job(conn, user_id, insert_video(conn, user_id))
    sql = (
        "INSERT INTO player_tracks (job_id, track_id, team, frames_visible, distance_px, "
        "distance_rel, heatmap, track) VALUES (:j, :t, :team, 1, 0, 0, '{}', '[]')"
    )
    conn.execute(text(sql), {"j": job_id, "t": 1, "team": "A"})
    assert_rejected(conn, sql, {"j": job_id, "t": 1, "team": "A"}, "pk_player_tracks")
    assert_rejected(conn, sql, {"j": job_id, "t": 2, "team": "C"}, "ck_player_tracks_team_valid")


def test_deleting_user_cascades(conn):
    user_id = insert_user(conn)
    job_id = insert_job(conn, user_id, insert_video(conn, user_id))
    conn.execute(
        text("INSERT INTO job_results (job_id, stats, annotated_key) VALUES (:j, '{}', 'k')"),
        {"j": job_id},
    )
    conn.execute(
        text("INSERT INTO sessions (token_hash, user_id, expires_at) VALUES ('\\x01', :u, now())"),
        {"u": user_id},
    )
    conn.execute(text("DELETE FROM users WHERE id = :u"), {"u": user_id})
    for table in ("videos", "jobs", "job_results", "sessions"):
        assert conn.execute(text(f"SELECT count(*) FROM {table}")).scalar_one() == 0
